export const AUTH_CONSTANTS = {
  ACCESS_TOKEN_EXPIRES_IN: process.env.ACCESS_TOKEN_EXPIRES_IN || '15m',
  REFRESH_TOKEN_EXPIRES_IN: process.env.REFRESH_TOKEN_EXPIRES_IN || '7d',
  REFRESH_COOKIE_NAME: 'refresh_token',
  REFRESH_COOKIE_MAX_AGE_MS: 7 * 24 * 60 * 60 * 1000
};